### DISCUSSION TITLE
请问下在ios 下嵌入的H5,在全屏播放的时候下拉关闭全屏播放,会出现原生的样式,如何去掉

### DISCUSSION THREAD

**Discussion by lmq352489099** [bytedance/xgplayer#872] [Q&A]
这是图片: 
![image](https://user-images.githubusercontent.com/37898934/218958877-85075059-f476-4a77-85a2-d623d4a5adc0.png)
这些是系统自带的

**Comment by gemxx** [comment]
iOS原生的样式无法修改

**Reply by gemxx** [reply]
> iOS原生的样式无法修改

这个结论有些不对，由于我这边未复现到此问题，查阅了一下[stackoverflow的解决方案](https://stackoverflow.com/questions/8911247/hide-iphone-html5-video-play-button)，可以尝试通过伪类修改shadow-dom样式：

```css
/* This used to work for the parent element of button divs */
/* But it does not work with newer browsers, the below doesn't hide the play button parent div */

*::-webkit-media-controls-panel {
  display: none!important;
  -webkit-appearance: none;
}

/* Old shadow dom for play button */

*::-webkit-media-controls-play-button {
  display: none!important;
  -webkit-appearance: none;
}

/* New shadow dom for play button */

/* This one works! */

*::-webkit-media-controls-start-playback-button {
  display: none!important;
  -webkit-appearance: none;
}
```
