### ISSUE TITLE
如何更改倍速文字颜色（默认色和选中色）

### ISSUE THREAD

**Issue by yi-jy** [bytedance/xgplayer#1507]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
^3.0.18

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
window10 chrome

**如何复现问题？ How to reproduce the problem?**

![image](https://github.com/bytedance/xgplayer/assets/10655307/670af1ab-fb19-41dd-9eb7-69c3e99d1d00)

**您期望的播放器正常行为是？ What did you expect to happen?**
需要类似 `commonStyle` 这种配置属性，可以配置倍速文字颜色（默认色和选中色）

**实际播放器的表现是？ What actually happened?**
没有相关属性配置。只能 css 修改颜色。对于通过 js 切换主题色不是很灵活，另外，对于 hover 交互颜色变化也不方便（需要通过 mouseenter 和 mouseleave 来模拟）；

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**

**Comment by hqh15** [comment]
我也没找到配置项，直接修改css了

```scss
:deep(.xgplayer .xg-options-list li:hover) {
  color: #fff;
}

:deep(.xgplayer .xg-options-list li.selected) {
  color: #fff;
}
```
