### ISSUE TITLE
父组件放大使用`transform: scale();`时进度条指示器会错位

### ISSUE THREAD

**Issue by AliusLeeOuO** [bytedance/xgplayer#1745]
**您使用的西瓜播放器版本是多少？ What version of xgplayer are you using?**
3.0.21

**您使用的操作系统和浏览器分别是？ What OS and browser are you using?**
MacOS 15.4 Chrome Current / Firefox

**如何复现问题？ How to reproduce the problem?**
```css
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

#root {
  height: 100lvh;
  width: 100lvw;
  overflow: hidden;
  display: flex;
  justify-content: center;
  align-items: center;
  transform: scale(1.5);
}
```
```tsx
import { useEffect } from 'react'
import './App.css'
import Player from 'xgplayer';
import "xgplayer/dist/index.min.css"

function App() {

  useEffect(() => {
    new Player({
      id: 'mse',
      url: 'url'
    });
  }, [])

  return (
    <>
      <div id="mse"></div>
    </>
  )
}

export default App

```
在父组件放大使用`transform: scale();`的时候进度条指示器会错位

**您期望的播放器正常行为是？ What did you expect to happen?**
进度指示器位置正常

**实际播放器的表现是？ What actually happened?**

![Image](https://github.com/user-attachments/assets/c42777a3-2a9f-43e2-93e9-a00c64eb728d)

**可填写您所在的公司和相关产品业务，方便我们提供更好的技术支持 You can write your company and product which uses xgplayer,  for helping us provide better technical support.**
