### ISSUE TITLE
画中画的pipConfig中的宽高无法更改

### ISSUE THREAD

**Issue by xiaopengtang** [bytedance/xgplayer#470]
版本：v2.14.4
skin：默认样式
描述：
默认皮肤中，有如下一段代码：
```css
  .xgplayer-skin-default.xgplayer-pip-active {
    position: fixed;
    right: 0;
    bottom: 200px;
    width: 320px!important;
    height: 180px!important;
    z-index: 110!important;
}
```
不是很懂，为啥下手一定要这么狠？导致内联样式中的宽高设置默认无效
